language: java
jdk:
  - openjdk8
  
addons:
  sonarcloud:
    organization: "sanjuthomas"
    token:
      secure: "f3c278a68bc1a0990451991362a7414d13dc5e4a"
      
script:
  - mvn -DexcludeTag=integration clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar package

after_success:
  - bash <(curl -s https://codecov.io/bash)
